### ISSUE TITLE
Header image

### ISSUE THREAD

**Issue by arzg** [KKPMW/sacredforest-vim#6]
Hi,

Is there any chance you could get a higher-resolution version of the header image in the README? I’ve tried Google Images, but nothing came up.

Thanks.

**Comment by KKPMW** [comment]
Hmm it should be quite high in resolution, if you click on it. [HERE] is a link to the cached github version. I am not sure there is a higher resolution version available.

**Comment by arzg** [comment]
Hm, looks like it’s 1976×1018, which is large enough for my purposes. Thanks.

Did you take this photo yourself? If not, where did you find it?

**Comment by KKPMW** [comment]
No no, definitely not myself. There was some website where you can search images by colors. I added a few colors from my colorscheme (it didn't have a name yet) and this image popped up as a match. That is the reason the theme was named "sacredforest" too.

But I do not remember what the website was.

**Comment by arzg** [comment]
Interesting backstory! I might see if I can find this site – sounds quite useful.
